### ISSUE TITLE
The game crashed whilst rendering screen Error: java.lang.NullPointerException: Rendering screen

### ISSUE THREAD

**Issue by dimitriepopescu** [dimitriepopescu/Dimitrie#1]
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 3/1/20 11:33 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at cpw.mods.fml.common.versioning.VersionRange.getLowerBoundString(VersionRange.java:573)
	at cpw.mods.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:54)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cpw.mods.fml.common.versioning.VersionRange.getLowerBoundString(VersionRange.java:573)
	at cpw.mods.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:54)

-- Screen render details --
Details:
	Screen name: cpw.mods.fml.client.GuiModsMissing
	Mouse location: Scaled: (0, 524). Absolute: (0, 0)
	Screen size: Scaled: (840, 525). Absolute: (1680, 1050). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 182799024 bytes (174 MB) / 603979776 bytes (576 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	U	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	U	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	U	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	U	academy-craft{1.0.7} [Academy Craft] (AcademyCraft-Mod-1.7.10.jar) 
	U	ActuallyAdditions{1.7.10-r21} [Actually Additions] (Actually-Additions-Mod-1.7.10.jar) 
	U	AncientWarfareAutomation{2.4.114-beta-MC1.7.10} [Ancient Warfare Automation] (Ancient-Warfare-Mod-1.7.10.jar) 
	U	AncientWarfare{2.4.114-beta-MC1.7.10} [Ancient Warfare Core] (Ancient-Warfare-Mod-1.7.10.jar) 
	U	AncientWarfareNEIPlugin{2.4.114-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (Ancient-Warfare-Mod-1.7.10.jar) 
	U	AncientWarfareNpc{2.4.114-beta-MC1.7.10} [Ancient Warfare NPCs] (Ancient-Warfare-Mod-1.7.10.jar) 
	U	AncientWarfareStructure{2.4.114-beta-MC1.7.10} [Ancient Warfare Structures] (Ancient-Warfare-Mod-1.7.10.jar) 
	U	animalbikes{1.7.10} [Animal Bikes] (Animal-Bikes-Mod-1.7.10.jar) 
	U	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (Applied-Energistics-2-Mod-1.7.10.jar) 
	U	arsmagica2{1.4.0.009} [Ars Magica 2] (Ars-Magica-2-Mod-1.7.10.jar) 
	U	Automagy{0.28.2} [Automagy] (Automagy-Mod-1.7.10.jar) 
	U	barrels{4.0} [The Barrels Mod] (Barrels-Mod-1.7.10.jar) 
	U	BattleTowers{1.5.1} [Battle Towers] (Battle-Towers-Mod-1.7.10.jar) 
	U	Baubles{1.0.1.10} [Baubles] (Baubles-Mod-1.7.10.jar) 
	U	BiblioCraft{1.11.6} [BiblioCraft] (BiblioCraft-Mod-1.7.10.jar) 
	U	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (Biomes-O-Plenty-Mod-1.7.10.jar) 
	U	blocklings{3.0.3} [Blocklings] (Blocklings-Mod-1.7.10.jar) 
	U	Botania{r1.8-249} [Botania] (Botania-Mod-1.7.10.jar) 
	U	BuildCraft|Core{7.1.23} [BuildCraft] (BuildCraft-Mod-1.7.10.jar) 
	U	BuildCraft|Transport{7.1.23} [BC Transport] (BuildCraft-Mod-1.7.10.jar) 
	U	BuildCraft|Factory{7.1.23} [BC Factory] (BuildCraft-Mod-1.7.10.jar) 
	U	BuildCraft|Silicon{7.1.23} [BC Silicon] (BuildCraft-Mod-1.7.10.jar) 
	U	BuildCraft|Robotics{7.1.23} [BC Robotics] (BuildCraft-Mod-1.7.10.jar) 
	U	BuildCraft|Energy{7.1.23} [BC Energy] (BuildCraft-Mod-1.7.10.jar) 
	U	BuildCraft|Builders{7.1.23} [BC Builders] (BuildCraft-Mod-1.7.10.jar) 
	U	camping{2.1g} [The Camping Mod 2] (Camping-Mod-1.7.10.jar) 
	U	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenters-Blocks-Mod-1.7.10.jar) 
	U	CompactMachines{1.7.10-1.21} [Compact Machines] (Compact-Machines-Mod-1.7.10.jar) 
	U	craftingtweaks{1.0.82} [Crafting Tweaks] (Crafting-Tweaks-Mod-1.7.10.jar) 
	U	eplus{3.0.2-d} [Enchanting Plus] (Enchanting-Plus-Mod-1.7.10.jar) 
	U	EE3{0.3.0.547} [Equivalent Exchange 3] (Equivalent-Exchange-3-Mod-1.7.10.jar) 
	U	ExtraPlanets{1.7.10-1.9.5} [Extra Planets] (Extra-Planets-Mod-1.7.10.jar) 
	U	ExtraUtilities{1.2.12} [Extra Utilities] (Extra-Utilities-Mod-1.7.10.jar) 
	U	Forestry{4.2.14.62} [Forestry for Minecraft] (Forestry-Mod-1.7.10.jar) 
	U	GalacticraftCore{3.0.12} [Galacticraft Core] (Galacticraft-Mod-1.7.10.jar) 
	U	GraviGun{4.0.0-beta} [GraviGun] (Gravity-Gun-Mod-1.7.10.jar) 
	U	Hats{4.0.1} [Hats] (Hats-Mod-1.7.10.jar) 
	U	IC2{2.2.827-experimental} [IndustrialCraft 2] (Industrial-Craft-2-Mod-Experimental-1.7.10.jar) 
	U	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.7.10.jar) 
	U	lucky{5.1.0} [Lucky Block] (Lucky-Block-Mod-1.7.10.jar) 
	U	MagicBees{2.4.3} [Magic Bees] (Magic-Bees-Mod-1.7.10.jar) 
	U	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-Mod-1.7.10.jar) 
	U	Morph{0.9.3} [Morph] (Morphing-Mod-1.7.10.jar) 
	U	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.7.10.jar) 
	U	Natura{2.2.0} [Natura] (Natura-Mod-1.7.10.jar) 
	U	nuclearcraft{V0.1 - 1.7.10} [Nuclear Craft] (Nuclear-Craft-Mod-1.7.10.jar) 
	U	PortalGun{4.0.0-beta-6} [PortalGun] (Portal-Gun-Mod-1.7.10.jar) 
	U	progressiveautomation{1.6.35} [Progressive Automation] (Progressive-Automation-Mod-1.7.10.jar) 
	U	quantumflux{1.7.10-1.3.4} [QuantumFlux] (QuantumFlux-Mod-1.7.10.jar) 
	U	Railcraft{9.12.2.1} [Railcraft] (Railcraft-Mod-1.7.10.jar) 
	U	runicdungeons{1.1.7b} [Runic Dungeons] (Runic-Dungeons-Mod-1.7.10.jar) 
	U	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-Mod-1.7.10.jar) 
	U	telepads{1.0.0} [Telepads] (TelePads-Mod-1.7.10.jar) 
	U	TwilightForest{2.3.7} [The Twilight Forest] (Twilight-Forest-Mod-1.7.10.jar) 
	U	waystones{1.0.12} [Waystones] (Waystones-Mod-1.7.10.jar) 
	U	xaerominimap{20.0.0} [Xaero's Minimap] (Xaeros-Minimap-Mod-1.7.10.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GTX 1070 Ti/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by dimitriepopescu** [comment]
Please Help me!
